#!/usr/bin/env node

const { program } = require('commander');
const chalk = require('chalk');
const fs = require('fs-extra');
const path = require('path');

const config = require('../lib/config');
const logger = require('../lib/logger');
const projectDetector = require('../lib/project');

/**
 * Get task for a specific phase
 */
function getPhaseTask(phaseNumber) {
  const phaseTasks = {
    1: {
      name: 'Requirements',
      role: 'Product Manager',
      firstTask: 'Analyze project requirements and create specification document',
      description: 'Product Manager - Define specifications'
    },
    2: {
      name: 'Planning',
      role: 'Software Architect',
      firstTask: 'Design system architecture and component structure',
      description: 'Software Architect - Design architecture'
    },
    3: {
      name: 'Implementation',
      role: 'Senior Developer',
      firstTask: 'Implement core functionality and business logic',
      description: 'Senior Developer - Build code'
    },
    4: {
      name: 'Verification',
      role: 'QA Lead',
      firstTask: 'Collect evidence package and test results',
      description: 'QA Lead - Test and validate'
    },
    5: {
      name: 'Release',
      role: 'Release Manager',
      firstTask: 'Coordinate final release preparation',
      description: 'Release Manager - Deploy and release'
    }
  };

  return phaseTasks[phaseNumber];
}

/**
 * Validate phase number
 */
function validatePhaseNumber(phaseNumber) {
  const num = parseInt(phaseNumber);

  if (isNaN(num)) {
    throw new Error(`Invalid phase number: ${phaseNumber}. Must be a number between 1-5.`);
  }

  if (num < 1 || num > 5) {
    throw new Error(`Phase number must be between 1 and 5. Got: ${num}`);
  }

  return num;
}

/**
 * Update checkpoint to specific phase
 */
async function updatePhaseCheckpoint(phaseNumber) {
  const projectConfig = await config.load();
  const checkpointPath = projectConfig.paths.recovery_checkpoint;

  // Ensure implementation directory exists
  await fs.ensureDir(path.dirname(checkpointPath));

  const phaseInfo = getPhaseTask(phaseNumber);
  const timestamp = new Date().toISOString();

  const checkpoint = `# CodeMaestro Recovery Checkpoint

**Last Updated:** ${timestamp}
**Phase:** ${phaseNumber}
**Role:** ${phaseInfo.role}
**Current Task:** ${phaseInfo.firstTask}

## Phase Progress

- 🎯 Jumped to Phase ${phaseNumber}: ${phaseInfo.name}

## Recovery Information

If this session is interrupted, use the following commands to resume:

1. **Current Phase:** \`${phaseNumber}\`
2. **Current Role:** ${phaseInfo.role}
3. **Resume Command:** \`/codem-next\`

## Task Guidance

**Next Steps:**
- Focus on: ${phaseInfo.firstTask}
- Role: ${phaseInfo.role}
- Use available tools and documentation to complete this task

---
*Auto-generated by CodeMaestro OpenCode*
`;

  await fs.writeFile(checkpointPath, checkpoint);
  return checkpointPath;
}

/**
 * Display phase information
 */
function displayPhaseInfo(phaseNumber, checkpointPath) {
  const phaseInfo = getPhaseTask(phaseNumber);

  console.log(chalk.bold.blue('🎯 CodeMaestro Phase Navigation'));
  console.log('═'.repeat(50));

  console.log(chalk.bold(`📊 Phase ${phaseNumber}:`), chalk.cyan(phaseInfo.name));
  console.log(`   ${phaseInfo.description}`);

  console.log(chalk.bold('\n👤 Role:'), chalk.green(phaseInfo.role));
  console.log(chalk.bold('🎯 Starting Task:'), phaseInfo.firstTask);

  console.log('\n' + chalk.green('🎯 Phase navigation successful!'));

  // Phase-specific guidance
  console.log('\n' + chalk.bold('💡 Phase Guidance:'));

  switch (phaseNumber) {
  case 1:
    console.log('• Define project requirements and objectives');
    console.log('• Create detailed specifications document');
    console.log('• Analyze competitive landscape');
    console.log('• Identify success criteria');
    break;
  case 2:
    console.log('• Design system architecture and components');
    console.log('• Create technical blueprints');
    console.log('• Plan development tasks and dependencies');
    console.log('• Estimate effort and resources');
    break;
  case 3:
    console.log('• Implement core functionality');
    console.log('• Follow established architectural patterns');
    console.log('• Write comprehensive tests');
    console.log('• Track progress and quality');
    break;
  case 4:
    console.log('• Collect evidence and test results');
    console.log('• Perform security and performance testing');
    console.log('• Validate against requirements');
    console.log('• Prepare for release decision');
    break;
  case 5:
    console.log('• Finalize release preparations');
    console.log('• Document lessons learned');
    console.log('• Execute deployment process');
    console.log('• Monitor initial performance');
    break;
  }

  console.log('\n' + chalk.bold('🔧 Available Commands:'));
  console.log(`• ${chalk.cyan('/codem-next')} - Continue to next task`);
  console.log(`• ${chalk.cyan('/codem-status')} - Check current progress`);
  console.log(`• ${chalk.cyan('/codem-commit')} - Create progress commits`);
  console.log(`• ${chalk.cyan('/codem-kb')} - Manage knowledge base`);

  if (phaseNumber >= 2) {
    console.log(`• ${chalk.cyan('/codem-research')} - Research and analysis tools`);
    console.log(`• ${chalk.cyan('/codem-lookup')} - Technical documentation lookup`);
  }

  console.log('\n' + chalk.gray(`Checkpoint saved: ${path.relative(process.cwd(), checkpointPath)}`));
  console.log('═'.repeat(50));
}

/**
 * Navigate to specific phase
 */
async function phaseCommand(phaseNumber) {
  try {
    logger.info(`Navigating to CodeMaestro Phase ${phaseNumber}...`);

    // Check if this is a CodeMaestro project
    if (!await projectDetector.isCodeMaestroProject()) {
      logger.error('Not a CodeMaestro project. Run `/codem-init` first.');
      console.log(chalk.blue(`
💡 To initialize a CodeMaestro project:
   ${chalk.cyan('/codem-init')}
      `));
      return;
    }

    // Validate phase number
    const validatedPhase = validatePhaseNumber(phaseNumber);

    // Get current phase for context
    const currentPhaseInfo = await projectDetector.getCurrentPhase();
    const currentPhase = currentPhaseInfo?.phase;

    if (currentPhase && currentPhase === validatedPhase) {
      console.log(chalk.yellow(`⚠️  Already in Phase ${validatedPhase}. Use \`/codem-next\` to continue.`));
      return;
    }

    // Update checkpoint to new phase
    const checkpointPath = await updatePhaseCheckpoint(validatedPhase);

    // Display information
    displayPhaseInfo(validatedPhase, checkpointPath);

    // Success message
    const action = currentPhase ? 'switched' : 'started';
    console.log(chalk.green(`\n✅ Successfully ${action} to Phase ${validatedPhase}: ${getPhaseTask(validatedPhase).name}`));

  } catch (error) {
    logger.error('Failed to navigate to phase', error);
    console.log(chalk.red(`\n❌ Error: ${error.message}`));
    console.log(chalk.gray('\nValid phases: 1-5'));
    console.log(chalk.gray('Usage: /codem-phase [1-5]'));
    process.exit(1);
  }
}

// CLI setup
program
  .name('codem-phase')
  .description('Navigate to a specific CodeMaestro phase (1-5)')
  .argument('<phase>', 'Phase number (1-5)')
  .action(phaseCommand);

// Export for testing
module.exports = {
  getPhaseTask,
  validatePhaseNumber,
  updatePhaseCheckpoint,
  displayPhaseInfo,
  phaseCommand
};

// Only parse if this file is run directly
if (require.main === module) {
  program.parse();
}